[server]
tcp = ["127.0.0.1:1888"]
uds = []                 # *nix only

[tmdb]
v4_auth = "ey..."
# proxy = "socks5h://localhost:1213"
language = "zh-CN"
timeout_s = 15

[[show]]
# 异世界药局
id = 129195
url = "https://www.dmhy.org/topics/list?keyword=异世界药局+{e:02}"

[[show]]
# 异世界舅舅
id = 127714
url = "https://www.dmhy.org/topics/list?keyword=异世界舅舅+{e:02}"

[[show]]
# better call saul
id = 60059
offset_days = 1
url = "https://thepiratebay10.org/search/Better%20call%20saul%201080p%20S{s:02}E{e:02}/1/99/200"

[[show]]
# 间谍过家家
id = 120089
url = "https://www.dmhy.org/topics/list?keyword=间谍过家家+{e:02}&sort_id=0&team_id=0&order=date-desc"

[[show]]
# 继母的拖油瓶
id = 129516
url = "https://www.dmhy.org/topics/list?keyword=继母的拖油瓶+{e:02}&sort_id=0&team_id=0&order=date-desc"
